[features]
seeds = true
skip-lint = false

[programs.localnet]
nor_registry = "NorReg1111111111111111111111111111111111111"

[programs.devnet]
nor_registry = "NorReg1111111111111111111111111111111111111"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
